CREATE DATABASE BP202Stadium

USE BP202Stadium

CREATE TABLE Stadiums
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(150),
	HourlyPrice DECIMAL,
	Capacity INT
)

CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	FullName VARCHAR(150),
	Email VARCHAR(600),
)